# fly.toml app configuration file generated for muddy-brook-8687 on 2023-06-09T16:24:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-brook-8687"
primary_region = "den"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 5000
